baseURL = "talebu.github.io"
title = "talebuのWebサイト"
theme ="hugo-theme-basic"
languageCode = "ja"
googleAnalytics = "G-SKQ9FJBTWW"
enableEmoji = false
copyright = "© 2023 <a href='https://twitter.com/talebujp' target='_blank'>@talebujp</a>."
description = "WebプログラマtalebuのWebサイトです。"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = "talebujp"

[Permalinks]
  post = "post/:slug"
  
[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "projects"
  url = "projects/"

[[params.menu]]
  name = "posts"
  url = "posts/"


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
